version: "3.8"
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: theproject
        ports:
            - "5432:5432"

    backend:
        build: ./backend
        environment:
            DATABASE_URL: postgres://user:password@postgres/theproject
        ports:
            - "8080:8080"
        depends_on:
            - postgres

    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
