[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "*"
diesel = { version = "2.2.4", features = ["postgres"] }
dotenvy = "0.15.7"
serde = { version = "*", features = ["derive"] }
serde_json = "1.0"
