services:


  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: theproject  # Define the default PostgreSQL user
      POSTGRES_PASSWORD: theproject  # Define the password for the user
      POSTGRES_DB: theproject
    ports:
      - "5432:5432"  # Map host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - app-network

  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://theproject:theproject@db:5432/theproject
    ports:
      - "3030:3030"  # Actix port mapping
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
