version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"  #Actix
    environment:
      DATABASE_URL: postgres://theproject:theproject@localhost/theproject  #DB
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: theproject  # Define the default PostgreSQL user
      POSTGRES_PASSWORD: theproject  # Define the password for the user
      POSTGRES_DB: theproject
    ports:
      - "5432:5432"  # Map host port 5432 to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: